version: "2"

services:
  cards-web:
    build: .
    user: "node"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./:/app
      - /app/exports/
      - /app/node_modules/
    ports:
      - "3000:3000"
    links:
      - cards-db
    container_name: cards-web

  cards-db:
    image: postgres:9.6.1
    ports:
      - "5430:5432"      
    environment:
      POSTGRES_USER: cards
      POSTGRES_PASSWORD: T4vbDpJMRGbL0rK
      POSTGRES_DB: cards
      POSTGRES_HOST: "localhost:5430"
    volumes:
      - './db-backup:/mnt/backup'
      - './scripts/postgres-backup.sh:/scripts/postgres-backup.sh:ro'
    restart: always 
    container_name: cards-db
